FROM golang:latest

WORKDIR /go/server

COPY go.mod go.sum /go/server/

RUN go env -w GOPROXY=https://goproxy.cn,direct \
    && go mod download -x

COPY ./ /go/server

RUN go build -o owo .

ENTRYPOINT ["/go/server/owo"]
# 构建出来的容器太大了，应该只保留最后编译出来的程序