FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y gcc \
    && apt-get install -y golang \
    && apt-get install -y python3 python3-pip \
    && apt-get install -y default-jre \
    && apt-get install -y default-jdk \
    && apt-get clean

WORKDIR /opt/

COPY executorserver mount.yaml /opt/

ENTRYPOINT ["/opt/executorserver"]